[project]
name = "rc-im-mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "uvicorn>=0.27.0",
    "fastapi>=0.110.0",
    "httpx>=0.28.0",
    "diskcache>=5.6.0",
    "requests>=2.31.0",
]
